Add support for a sample_weight argument to fast_numba_auc().
diditforlulz273/fastauc pull request #3
Opened 2023-01-17 18:48 UTC by Agade09

2023-01-18 14:50 UTC, diditforlulz273 requested changes

2023-01-18 14:50 UTC, diditforlulz273 commented on fastauc/fast_auc.py
> +def fast_numba_auc(y_true: np.array, y_prob: np.array,sample_weight=np.array([])):
plz. a space after comma

2023-01-18 14:50 UTC, diditforlulz273 commented on fastauc/fast_auc.py
> +    if len(sample_weight)>0:
spaces around >

2023-01-18 14:50 UTC, diditforlulz273 commented on fastauc/fast_auc.py
> +        weight = (sample_weight[i] if len(sample_weight)>0 else 1.0)
spaces around >

2023-01-18 14:50 UTC, diditforlulz273 commented on fastauc/fast_auc.py
> +        tps = prev_tps + y_true[i]*weight
spaces around * operator

2023-01-18 14:50 UTC, diditforlulz273 commented on fastauc/fast_auc.py
> +        fps = prev_fps + (1 - y_true[i])*weight
spaces around * operator

2023-01-18 14:50 UTC, diditforlulz273 commented on fastauc/fast_auc.py
> +def fast_auc(y_true: np.array, y_prob: np.array, sample_weight=None) -> Union[float, str]:
update existing docstring with the new parameter description

2023-01-18 14:50 UTC, diditforlulz273 commented on fastauc/fast_auc.py
> +        tps = np.cumsum(y_true*sample_weight)[threshold_idxs]
spaces around * operator

2023-01-18 14:51 UTC, diditforlulz273 commented
Also, if you add sample weights to two functions, please add it to the C++ one to make changes and logic similar

2023-01-18 16:52 UTC, diditforlulz273 requested changes
I ask for code style changes and, more importantly, to not use mutable default arguments - the previous approach with None is the classic actually.

2023-01-18 16:52 UTC, diditforlulz273 commented on fastauc/cpp_auc.cpp
> +        if constexpr(std::is_same<tuple_type,std::tuple<bool,float,float>>::value){
plz. spaces after commas :)

2023-01-18 16:52 UTC, diditforlulz273 commented on fastauc/cpp_auc.cpp
> +template<typename tuple_type> float auc_kernel(float* ts, bool* st, size_t len,float* sample_weight) {
space after comma too

2023-01-18 16:52 UTC, diditforlulz273 commented on fastauc/cpp_auc.cpp
> +    if constexpr(std::is_same<tuple_type,std::tuple<bool,float,float>>::value){
spaces after commas plz.

2023-01-18 16:52 UTC, diditforlulz273 commented on fastauc/cpp_auc.cpp
> +        if(n_sample_weights>0){
spaces around > operator

2023-01-18 16:52 UTC, diditforlulz273 commented on fastauc/cpp_auc.cpp
> +            return auc_kernel<std::tuple<bool,float,float>>(ts, st, len, sample_weight);
spaces after commas

2023-01-18 16:52 UTC, diditforlulz273 commented on fastauc/cpp_auc.cpp
> +            return auc_kernel<std::tuple<bool,float>>(ts, st, len, sample_weight);
spaces after commas

2023-01-18 16:52 UTC, diditforlulz273 commented on fastauc/fast_auc.py
> +    def roc_auc_score(self, y_true: np.array, y_score: np.array, sample_weight=np.array([],dtype=np.float32)) -> float:
that's pretty bad actually - never declare mutable objects(like lists arrays etc) as default parameters in python:

Python’s default arguments are evaluated once when the function is defined, not each time the function is called (like it is in say, Ruby). This means that if you use a mutable default argument and mutate it, you will and have mutated that object for all future calls to the function as well.

You can find code examples here:
[click](https://www.30secondsofcode.org/articles/s/python-mutable-default-arguments)

2023-01-18 16:52 UTC, diditforlulz273 commented on fastauc/fast_auc.py
> +def fast_auc(y_true: np.array, y_prob: np.array, sample_weight: np.array=np.array([])) -> Union[float, str]:
that's pretty bad actually - never declare mutable objects(like lists arrays etc) as default parameters in python:

Python’s default arguments are evaluated once when the function is defined, not each time the function is called (like it is in say, Ruby). This means that if you use a mutable default argument and mutate it, you will and have mutated that object for all future calls to the function as well.

You can find code examples here:
[click](https://www.30secondsofcode.org/articles/s/python-mutable-default-arguments)

2023-01-18 16:52 UTC, diditforlulz273 commented on fastauc/fast_auc.py
> +def fast_numba_auc(y_true: np.array, y_prob: np.array, sample_weight: np.array=np.array([])):
that's pretty bad actually - never declare mutable objects(like lists arrays etc) as default parameters in python:

Python’s default arguments are evaluated once when the function is defined, not each time the function is called (like it is in say, Ruby). This means that if you use a mutable default argument and mutate it, you will and have mutated that object for all future calls to the function as well.

You can find code examples here:
[click](https://www.30secondsofcode.org/articles/s/python-mutable-default-arguments)

2023-01-18 17:46 UTC, Agade09 commented
I struggled to get numba to take None. That is the reason I gave a numpy array as default. I pushed a workaround by having a wrapper python function before calling numba. I didn't find better.

2023-01-21 21:54 UTC, diditforlulz273 commented
@Agade09 I think it would be faster if I correct some stuff myself, please re-PR the current code to the new branch I created, agade_2

2023-01-22 15:36 UTC, closed without merging